<div id="content-footer">
	<div class="first-content-footer">
		<h3>Partenaires :</h3>
		<div>
			<a href="http://www.ratp.fr/fr/" target=_blank class="lien-ratp" title="La carte Navigo de la ratp vous permet d'avoir des reductions !"></a>
			<a href="http://www.amazon.fr/" target=_blank class="lien-amazon" title="Car j'ais pris mes exemples de produits chez eux !"></a>
			<img src="<?php echo $this->baseUrl()."/images/partenaires/ratp.png" ?>" alt="La carte Navigo de la ratp vous permet d'avoir des reductions !" title="La carte Navigo de la ratp vous permet d'avoir des reductions !" />
			<img src="<?php echo $this->baseUrl()."/images/partenaires/amazon.png" ?>" alt="Car j'ais pris mes exemples de produits chez eux !" title="Car j'ais pris mes exemples de produits chez eux !" />
		</div>
	</div>
	<div class="second-content-footer">
		<p>De tout et de rien est un site de e-commerce proposant des produits hors du commun souvent relier à des choses inutiles.<br/><br/>
		Adresse de l'entreprise : 0 rue de l'Inutilité, Saint-Objet-Cassé, xx xxx
		</p>
	</div>
	<div class="last-content-footer">
		<p>
			<a class="footer-panier" href="<?php echo $this->baseUrl('panier/afficher')?>" title="Accéder à votre panier">Accès au panier</a>
		</p>
		<p class="p-footer-admin">
			<a class="footer-admin popup-link" href="<?php echo $this->baseUrl("admin/connexion")?>" title="Accès vers la gestion du site">Accès commerçant</a>
		</p>
		<p class="footer-contact" title="A venir">Contact</p>
	</div>
</div>